title: "Peaceful Science"
languageCode: "en-us"
baseURL: https://peacefulscience.org
timeZone: America/Chicago 
enableGitInfo: true
disableAliases: true

server:
  headers:
    - for: /font/*.woff2
      values:
        Access-Control-Allow-Origin: "*"

minify:
  disableXML: true

related:
  includeNewer: true
  indices:
  - name: categories
    weight: 100
  - name: authors
    weight: 50
  - name: section
    weight: 50
  threshold: 80
  toLower: false
  
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
        
cache:
  getjson:
    dir: :cacheDir/:project
    maxAge: 23hr

mediaTypes:
  text/prs.netlify:
    suffixes: [""]
    delimiter: ""
    
outputformats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  redir:
    mediatype: text/prs.netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  precompute:
    notAlternative: true
    weight: 1
    permalinkable: False
  HTML:
    weight: 2 
  xrefposted:
    mediaType: "application/xml"
    basename: posted
    path: .xref
    notAlternative: true
  xrefbook:
    mediaType: "application/xml"
    basename: book
    path: .xref
    notAlternative: true
  xrefconf:
    mediaType: "application/xml"
    basename: conf
    path: .xref
    notAlternative: true
  print:
    path: _prince
    mediaType: "text/html"
    notAlternative: true
    isPlainText: false
    isHTML: true
    isUgly: true
    path: _prince
    permalinkable: false
   
outputs:
  home: ["HTML", "algolia", "RSS", "redir", "xrefconf", "xrefposted", "xrefbook"]
  page: ["HTML"]

params:
  baseGitHub: "https://github.com/PeacefulScience/peacefulscience.org/"
  sitemap_min_date: "2021-09-10"
  algolia:
    vars: ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params: ["categories", "tags"]
  imagecdn: 8l2ic7fx.cdn.imgeng.in
  logo: /img/design/logo-black-square.png
  doiprefix: 10.54739

paginate: 24

googleAnalytics: G-BHPH29YM44

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
 
sitemap:
  priority: 0.5

permalinks: 
  article: /:sections/:title/

