title: "Peaceful Science"
baseURL: "http://test.peacefulscience.org/"
languageCode: "en-us"

enableGitInfo: true


params:
  headerType: none

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

sitemap:
  priority: 0.5

permalinks: 
  article: /:title/

theme: flexible-seo-hugo
