title: "Peaceful Science"
baseURL: "http://test.peacefulscience.org/"
languageCode: "en-us"

enableGitInfo: true

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

sitemap:
  priority: 0.5

permalinks: 
  article: /:title/

theme: hyde-x
