title: "Peaceful Science"
baseURL: "https://peacefulscience.netlify.app/"
languageCode: "en-us"

enableGitInfo: true
disableAliases: true

module:
  imports:
  - path: hugo-module-tnd-imgix

related:
  includeNewer: true
  indices:
  - name: categories
    weight: 100
  - name: authors
    weight: 50
  - name: series
    weight: 100
  - name: section
    weight: 50
  threshold: 80
  toLower: false
  
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true


mediaTypes:
  text/prs.netlify:
    suffixes: [""]
    delimiter: ""
    
outputformats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  redir:
    mediatype: text/prs.netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
    
outputs:
  home: ["HTML", "RSS", "redir"]
params:
  tnd_imgix:
    domain: imgix.project.net
  algolia:
    vars: ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params: ["categories", "tags"]
  headerType: none


    
menu:
  main:
  - name: Home
    url: /
    weight: -120
  - name: Articles
    url: /archive/
    weight: -115  
  - name: Book
    url: /genealogical-adam-eve/
    weight: -109
  - name: Forum
    url: /forum/
    weight: -108
  - name: Mission and Values
    url: /articles/mission-and-values/
    weight: -100


taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

sitemap:
  priority: 0.5

permalinks: 
  article: /:sections/:title/

theme: flexible-seo-hugo
