[build]
  command = "hugo"
  publish = "public/"
  
[context.production.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
  
[[plugins]]
package = "netlify-plugin-checklinks"