[build]
command = "hugo -b $URL"
publish = "public/"

[build.environment]
HUGO_VERSION = "0.81.0"

[context.production.environment]
HUGO_ENV = "production"
  
[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts"

