[build]
command = "hugo -b $URL"
publish = "public/"

[context.production]
command = "make production"

[build.environment]
HUGO_VERSION = "0.89.0"
HUGO_ENV = "development"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts -F"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts -F"

[dev]
command =  "hugo -w --buildDrafts -F "
framework = "#static"
publish = "./public/"
