[build]
command = "hugo mod clean && hugo -b $URL"
publish = "public/"

[build.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "development"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts"


[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
